image: docker.intern.molit.eu/ig-pipeline

cache:
  key: ${CI_COMMIT_REF_SLUG}

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - export _JAVA_OPTIONS="-Xmx11g -Xms4g"
  script:
    - pwd
    - ls -lahs
    - cat 12443453453.txt
  artifacts:
    name: "$CI_PROJECT_NAME"
    when: always
    paths:
      - output/
      - /builds/molit/fhir/profiling/terminology-ig/*.md
  tags: 
    - docker

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r output/* public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  when: manual
  tags:
    - docker

publish-nexus:
  stage: deploy    
  script:
    - npm config set registry https://nexus.intern.molit.eu/repository/npm-internal/
    - npm config set //nexus.intern.molit.eu/repository/npm-internal/:_authToken ${NPM_TOKEN}
    - npm publish ./output/package.tgz
  when: manual
  tags: 
    - docker
