image: ghcr.io/echinos-eu/hl7-ig-builder-docker:release

cache:
  key: ${CI_COMMIT_REF_SLUG}

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - export _JAVA_OPTIONS="-Xmx8g -Xms4g"
  script:
#    - sushi
    - java -Xmx6G -jar /opt/publisher/publisher.jar -ig .
  artifacts:
    name: "$CI_PROJECT_NAME"
#    when: always
    paths:
#      - $CI_PROJECT_DIR/
      - output/
  tags: 
    - docker

pages:
  stage: deploy
  script:
    - mkdir public
    - cp -r output/* public
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  when: manual
  tags:
    - docker

publish-nexus:
  stage: deploy    
  script:
    - npm config set registry https://nexus.intern.molit.eu/repository/npm-internal/
    - npm config set //nexus.intern.molit.eu/repository/npm-internal/:_authToken ${NPM_TOKEN}
    - npm publish ./output/package.tgz
  when: manual
  tags: 
    - docker
