# ╭─────────────────────────────────ImplementationGuide-fish.json──────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  http://build.fhir.org/ig/HL7/fhir-shorthand/branches/beta/sushi.html#ig-development           │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: molitVITU
canonical: http://molit.eu/fhir/vitu
version: 0.1.0
name: TrialImplementationGuide
title: Clinical Trial Implementation Guide
status: draft
publisher: Molit Institute gGmbH
contact:
  - name: Molit Institute gGmbH
    telecom:
      - system: email
        value: mailto:info@molit.eu
description: An Implementation Guide for a FHIR based trial management
license: CC0-1.0
fhirVersion: 4.0.1
parameters:
  apply-publisher: true
  apply-contact: true
  show-inherited-invariants: false
copyrightYear: 2020+
releaseLabel: ci-build
#dependencies:
#  hl7.fhir.uv.genomics-reporting: dev
#  de.einwilligungsmanagement: current


# ╭─────────────────────────────────────────────ig.ini─────────────────────────────────────────────╮
# │  To use a provided ig-data/ig.ini file, delete the "template" property below.                  │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
#template: fhir.base.template#current

# ╭───────────────────────────────────────package-list.json────────────────────────────────────────╮
# │  To use a provided ig-data/package-list.json file, delete the "history" property below.        │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
#history:
#  current: http://build.fhir.org/ig/example/example-ig
#  0.0.1:
#    fhirversion: 4.0.1
#    date: 2099-01-01
#    desc: Initial STU ballot (Mmm yyyy Ballot)
#    path: http://example.org/fhir/STU1
#    status: ballot
#    sequence: STU 1
#    current: true

# ╭───────────────────────────────────────package-list.json────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
#menu:
#  IG Home: index.html
#  Table of Contents: toc.html
#  Artifacts Summary: artifacts.html
#  Other Resources:
#    "FHIR Spec ": new-tab {{site.data.fhir.path}}index.html

#pages:
#  index.md:
#    title: Example Home
#  implementation.xml:
#  examples.xml:
#    title: Examples Overview
#    simpleExamples.xml:
#    complexExamples.xml:

# Defines the groups of the IG