# ╭─────────────────────────────────ImplementationGuide-fish.json──────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see:                                                                    │
# │  http://build.fhir.org/ig/HL7/fhir-shorthand/branches/beta/sushi.html#ig-development           │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: molit.fhir.common-terminology
canonical: http://molit.eu/fhir
version: 0.3.0
name: TerminologyImplementationGuide
title: MOLIT Common Terminology IG package
description: MOLIT Common Terminology IG package
status: active
publisher:
  name: Molit Institute gGmbH
  url: https://molit.eu
  email: info@molit.eu
fhirVersion: 4.0.1
parameters:
  apply-publisher: true
  apply-contact: true
  no-narrative: [CodeSystem/*, ValueSet/*, ConceptMap/*]
  no-validate: [CodeSystem/*, ValueSet/*]

copyrightYear: 2024+
releaseLabel: ci-build
#dependencies:
#  hl7.fhir.uv.genomics-reporting: dev
#  de.einwilligungsmanagement: current


# ╭─────────────────────────────────────────────ig.ini─────────────────────────────────────────────╮
# │  To use a provided ig-data/ig.ini file, delete the "template" property below.                  │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
#template: fhir.base.template#current

# ╭───────────────────────────────────────package-list.json────────────────────────────────────────╮
# │  To use a provided ig-data/package-list.json file, delete the "history" property below.        │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
#history:
#  current: http://build.fhir.org/ig/example/example-ig
#  0.0.1:
#    fhirversion: 4.0.1
#    date: 2099-01-01
#    desc: Initial STU ballot (Mmm yyyy Ballot)
#    path: http://example.org/fhir/STU1
#    status: ballot
#    sequence: STU 1
#    current: true

# ╭───────────────────────────────────────package-list.json────────────────────────────────────────╮
# │  To use a provided ig-data/input/includes/menu.xml file, delete the "menu" property below.     │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
#menu:
#  IG Home: index.html
#  Table of Contents: toc.html
#  Artifacts Summary: artifacts.html
#  Other Resources:
#    "FHIR Spec ": new-tab {{site.data.fhir.path}}index.html

#pages:
#  index.md:
#    title: Example Home
#  implementation.xml:
#  examples.xml:
#    title: Examples Overview
#    simpleExamples.xml:
#    complexExamples.xml:

# Defines the groups of the IG